apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1$2$3
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

  name: redirect-back-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /(api|admin)(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service #TODO: Change this to the name of the service when we have it
            port: 
              number: 5000

  