image:
  repository: moviemanagercloud
  name: movie-manager-backapi
  tag: latest

service:
  type: ClusterIP
  protocol: TCP
  port: 5000

env:
  DB_NAME: movie_manager
  DB_USER: totolastico
  DB_PASSWORD: 4AL5DxL9!iW
  DB_HOST: postgres
  DB_PORT: 5432

resources:
  limits:
    cpu: "0.2"
    memory: "250Mi"
  requests:
    cpu: "0.1"
    memory: "100Mi"
