apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  RedisHost: "{{ .Values.env.RedisHost }}"
  HostRabbitmq: "{{ .Values.env.HostRabbitmq }}"
  DB_NAME: "{{ .Values.env.DB_NAME }}"
  DB_USER: "{{ .Values.env.DB_USER }}"
  DB_PASSWORD: "{{ .Values.env.DB_PASSWORD }}"
  DB_HOST: "{{ .Values.env.DB_HOST }}"
  DB_PORT: "{{ .Values.env.DB_PORT }}"