apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: {{ .Values.secrets.POSTGRES_DB | b64enc }}